name: Coupang Item Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          pip install playwright pandas
          playwright install chromium

      - name: 스크레이퍼 실행
        run: python scraper.py

      - name: 결과 저장 및 업데이트
        run: |
          git config --global user.name "Scraper-Bot"
          git config --global user.email "bot@github.com"
          git add coupang_items.csv || exit 0
          git commit -m "Update data $(date)" || exit 0
          git push
